### ISSUE TITLE
File Not Found: #import <plaid_ios_sdk/PLDDefines.h>

### ISSUE THREAD

**Issue by chrisnolet** [simonlevy5/plaid-ios-link#12]
I'm getting an error when I use Cocoapods to import the Plaid SDK and PlaidLink together. My Podfile contains:

```
pod 'plaid-ios-link', '~> 0.1'
pod 'plaid-ios-sdk', '~> 0.3'
```

I get an error when compiling: `'plaid_ios_sdk/PLDDefines.h' file not found` for every occurrence of `#import <plaid_ios_sdk/PLDDefines.h>`.

I can fix the error by changing `#import <plaid_ios_sdk/PLDDefines.h>` to `#import <plaid-ios-sdk/PLDDefines.h>` (with hyphens instead of underscores).

**Comment by simonlevy5** [comment]
@chrisnolet I recommend just importing one of those pods. 'plaid-ios-sdk' is a dependency of 'plaid-ios-link', which will automatically import it and package it in a way that the imports used will work.

**Comment by chrisnolet** [comment]
Thanks for your quick response. Importing just `plaid-ios-link` gives me the same error. (`plaid-ios-sdk` is a dependency, but it's the same version, resulting in the same issues). I believe the only way to fix this is to update the `#import` statement. Is that right?

From the Podfile.lock:

```
plaid-ios-link: b508d0cb64007ec036c98ff7f2f0ec1913e8467b
plaid-ios-sdk: e9865b0fe6a79b3d30d886171d7a26f7e1408935
```
