### ISSUE TITLE
Pod trunk still at 0.1.1

### ISSUE THREAD

**Issue by MaximusMcCann** [simonlevy5/plaid-ios-link#16]
Would like to have the pod trunk updated to have the 0.2.1 tag

Quick reference: https://guides.cocoapods.org/terminal/commands.html#pod_trunk_push

Cheers!

**Comment by simonlevy5** [comment]
@MaximusMcCann I tagged a release/tag as 0.2.1, it should be available. Let me know if not!

**Comment by MaximusMcCann** [comment]
@simonlevy5 hmmm, cocoapods site is still showing 0.1.1: https://cocoapods.org/?q=plaid
I do see the tag in this github repo though, cheers!

**Comment by simonlevy5** [comment]
@MaximusMcCann A crap, sorry, I misread. I can't do this immediately, but will make sure I get it done within the day. Sorry for the delay!

**Comment by MaximusMcCann** [comment]
@simonlevy5 All bueno, no sweat.  Appreciate the prompt responses!!

**Comment by harshpreet93** [comment]
@simonlevy5 pod install is giving me an error when I try to pod install 0.2.1. 
![image](https://cloud.githubusercontent.com/assets/3123326/16719436/10b5c46c-46df-11e6-89bf-f079c5a24539.png) Any help would be greatly appreciated as I am new to cocoapods and iOS development!

**Comment by MaximusMcCann** [comment]
@simonlevy5 try running `pod repo update` first and then try `pod install` again

**Comment by simonlevy5** [comment]
@MaximusMcCann Sorry. I hope to have this done today. I'm waiting on the Cocoapods dev team to re-assign the repository to my personal e-mail address as simon@vouch.com no longer exists, sadly.

**Comment by MaximusMcCann** [comment]
All good cheers!
